Feature/detail page
team-dongle/dongle-fe-v2 pull request #2
Opened 2024-12-19 10:53 UTC by zxcv2987

- 상세페이지 구현 완료
- Tap Groups를 활용한 소개, 활동보고서 탭 구현
- 병렬 라우팅을 활용한 활동보고서 모달 구현
- modal 오픈 시 document.body 스크롤 hidden

2024-12-19 11:07 UTC, nyongone requested changes
introduction 페이지 이름이 너무 긴 것 같아서 그냥 info로 줄이고,
feed 보단 그냥 reports가 나을 것 같습니다.

2024-12-19 11:07 UTC, nyongone commented on app/(service)/(detail)/[id]/@tabs/feed/@modal/[reportId]/page.tsx
> +          <p className="text-lg text-zinc-700">{result.content}</p>
result.content `\n`로 split하고 map함수 사용해서 띄어쓰기 구현해주세요.

2024-12-19 11:07 UTC, nyongone commented on app/(service)/(detail)/[id]/@tabs/feed/page.tsx
feed보단 reports가 낫지 않을까요?
저희 서비스 내에서 feed란 워딩을 쓰는 곳이 없어요..

2024-12-19 11:07 UTC, nyongone commented on components/domain/detail/tabs.tsx
컴포넌트 이름 파스칼케이스로 작성해주세요.

2024-12-19 11:33 UTC, zxcv2987 commented on app/(service)/(detail)/[id]/@tabs/feed/@modal/[reportId]/page.tsx
> +          <p className="text-lg text-zinc-700">{result.content}</p>
띄어쓰기는 JSX에서 알아서 해석 가능한 것 같네요. whitespace-pre-wrap css 속성으로 줄바꿈만 적용시키겠습니다

2024-12-19 13:00 UTC, nyongone commented on app/(service)/(detail)/[id]/@tabs/feed/@modal/[reportId]/page.tsx
> +          <p className="text-lg text-zinc-700">{result.content}</p>
아 정정하겠습니다
띄어쓰기가 아니라 줄바꿈이였습니다...;;

2024-12-19 13:02 UTC, nyongone commented on app/(service)/(detail)/[id]/@tabs/feed/@modal/[reportId]/page.tsx
> +          <p className="text-lg text-zinc-700">{result.content}</p>
````jsx
result.content.split("\n").map((paragraph, idx) => <p key={idx} {rest}>{paragraph}</p>)
````

2024-12-19 13:05 UTC, nyongone requested changes

2024-12-19 13:05 UTC, nyongone commented on components/domain/detail/tabs.tsx
`tabs.tsx` -> `Tabs.tsx`

2024-12-19 13:05 UTC, nyongone commented on app/(service)/(detail)/[id]/@tabs/reports/@modal/[reportId]/page.tsx
> +          <p className="whitespace-pre-wrap text-lg text-zinc-700">
문단 줄바꿈 넣어주세요~

2024-12-20 07:36 UTC, nyongone approved these changes
굿 👍

2024-12-20 07:36 UTC, merged